// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRental.Model;

#nullable disable

namespace MovieRental.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230519132312_SeedExampleData")]
    partial class SeedExampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("MovieRental.Model.Customer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "93117 Evansville",
                            FirstName = "Shelly",
                            LastName = "Estrada",
                            Phone = "1-871-372-7263"
                        },
                        new
                        {
                            Id = 2,
                            Address = "92160 Evansville",
                            FirstName = "Althea",
                            LastName = "Richardson",
                            Phone = "(575) 618-6840"
                        },
                        new
                        {
                            Id = 3,
                            Address = "31614 Dover",
                            FirstName = "Galena",
                            LastName = "Kelly",
                            Phone = "(722) 267-4538"
                        },
                        new
                        {
                            Id = 4,
                            Address = "74577 Atlanta",
                            FirstName = "Cade",
                            LastName = "Casey",
                            Phone = "1-724-363-8148"
                        },
                        new
                        {
                            Id = 5,
                            Address = "99675 Des Moines",
                            FirstName = "Candace",
                            LastName = "Stevenson",
                            Phone = "1-765-565-2433"
                        },
                        new
                        {
                            Id = 6,
                            Address = "63724 Hartford",
                            FirstName = "Lacota",
                            LastName = "Macdonald",
                            Phone = "1-437-949-1331"
                        },
                        new
                        {
                            Id = 7,
                            Address = "36002 Olathe",
                            FirstName = "Elijah",
                            LastName = "Mcneil",
                            Phone = "1-245-286-2854"
                        },
                        new
                        {
                            Id = 8,
                            Address = "25335 Burlington",
                            FirstName = "Kelsey",
                            LastName = "Watts",
                            Phone = "1-271-128-2267"
                        },
                        new
                        {
                            Id = 9,
                            Address = "77570 Atlanta",
                            FirstName = "Iola",
                            LastName = "Williamson",
                            Phone = "1-886-680-7164"
                        },
                        new
                        {
                            Id = 10,
                            Address = "76957 Hilo",
                            FirstName = "Nola",
                            LastName = "Joyce",
                            Phone = "1-714-644-2452"
                        },
                        new
                        {
                            Id = 11,
                            Address = "94770 Jacksonville",
                            FirstName = "Louis",
                            LastName = "Strickland",
                            Phone = "1-430-859-3268"
                        },
                        new
                        {
                            Id = 12,
                            Address = "82307 Green Bay",
                            FirstName = "Lamar",
                            LastName = "Benjamin",
                            Phone = "1-530-552-9128"
                        },
                        new
                        {
                            Id = 13,
                            Address = "82411 Lakewood",
                            FirstName = "Audrey",
                            LastName = "Everett",
                            Phone = "(548) 188-6377"
                        },
                        new
                        {
                            Id = 14,
                            Address = "73836 Metairie",
                            FirstName = "Noah",
                            LastName = "Klein",
                            Phone = "1-127-947-2433"
                        },
                        new
                        {
                            Id = 15,
                            Address = "33489 Naperville",
                            FirstName = "Lucius",
                            LastName = "Mullen",
                            Phone = "(667) 450-1968"
                        });
                });

            modelBuilder.Entity("MovieRental.Model.Movie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
                            Title = "The Shawshank Redemption",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 2,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.",
                            Title = "The Godfather",
                            Year = "1972"
                        },
                        new
                        {
                            Id = 3,
                            Copies = 3,
                            Genre = "action, crime, drama",
                            Plot = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Title = "The Dark Knight",
                            Year = "2008"
                        },
                        new
                        {
                            Id = 4,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Title = "The Godfather: Part II",
                            Year = "1974"
                        },
                        new
                        {
                            Id = 5,
                            Copies = 3,
                            Genre = "drama",
                            Plot = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Title = "12 Angry Men",
                            Year = "1957"
                        },
                        new
                        {
                            Id = 6,
                            Copies = 3,
                            Genre = "biography, drama, history",
                            Plot = "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
                            Title = "Schindler's List",
                            Year = "1993"
                        },
                        new
                        {
                            Id = 7,
                            Copies = 3,
                            Genre = "action, adventure, fantasy",
                            Plot = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = "2003"
                        },
                        new
                        {
                            Id = 8,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Title = "Pulp Fiction",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 9,
                            Copies = 3,
                            Genre = "action, adventure, fantasy",
                            Plot = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Year = "2001"
                        },
                        new
                        {
                            Id = 10,
                            Copies = 3,
                            Genre = "western",
                            Plot = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Title = "The Good, the Bad and the Ugly",
                            Year = "1966"
                        },
                        new
                        {
                            Id = 11,
                            Copies = 3,
                            Genre = "drama, romance",
                            Plot = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            Title = "Forrest Gump",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 12,
                            Copies = 3,
                            Genre = "drama",
                            Plot = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Title = "Fight Club",
                            Year = "1999"
                        },
                        new
                        {
                            Id = 13,
                            Copies = 3,
                            Genre = "adventure, fantasy",
                            Plot = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = "2002"
                        },
                        new
                        {
                            Id = 14,
                            Copies = 3,
                            Genre = "action, adventure, sci-fi",
                            Plot = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            Id = 15,
                            Copies = 3,
                            Genre = "action, adventure, fantasy",
                            Plot = "When a tribal man is arrested for a case of alleged theft, his wife turns to a human-rights lawyer to help bring justice.",
                            Title = "Star Wars: Episode V - The Empire Strikes Back",
                            Year = "1980"
                        },
                        new
                        {
                            Id = 16,
                            Copies = 3,
                            Genre = "action, sci-fi",
                            Plot = "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
                            Title = "The Matrix",
                            Year = "1999"
                        },
                        new
                        {
                            Id = 17,
                            Copies = 3,
                            Genre = "biography, crime, drama",
                            Plot = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
                            Title = "Goodfellas",
                            Year = "1990"
                        },
                        new
                        {
                            Id = 18,
                            Copies = 3,
                            Genre = "drama",
                            Plot = "After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.",
                            Title = "One Flew Over the Cuckoo's Nest",
                            Year = "1975"
                        },
                        new
                        {
                            Id = 19,
                            Copies = 3,
                            Genre = "drama, mystery, thriller",
                            Plot = "In the Fall of 1963, a Korean War veteran and criminal pleads insanity and is admitted to a mental institution, where he rallies up the scared patients against the tyrannical nurse.",
                            Title = "Se7en",
                            Year = "1995"
                        },
                        new
                        {
                            Id = 20,
                            Copies = 3,
                            Genre = "drama, family, fantasy",
                            Plot = "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
                            Title = "It's a Wonderful Life",
                            Year = "1946"
                        },
                        new
                        {
                            Id = 21,
                            Copies = 3,
                            Genre = "action, adventure, drama",
                            Plot = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
                            Title = "Seven Samurai",
                            Year = "1954"
                        },
                        new
                        {
                            Id = 22,
                            Copies = 3,
                            Genre = "crime, drama, thriller",
                            Plot = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Title = "The Silence of the Lambs",
                            Year = "1991"
                        },
                        new
                        {
                            Id = 23,
                            Copies = 3,
                            Genre = "action, drama, war",
                            Plot = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Title = "Saving Private Ryan",
                            Year = "1998"
                        },
                        new
                        {
                            Id = 24,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            Title = "City of God",
                            Year = "2002"
                        },
                        new
                        {
                            Id = 25,
                            Copies = 3,
                            Genre = "adventure, drama, sci-fi",
                            Plot = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
                            Title = "Interstellar",
                            Year = "2014"
                        },
                        new
                        {
                            Id = 26,
                            Copies = 3,
                            Genre = "comedy, drama, romance",
                            Plot = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.",
                            Title = "Life Is Beautiful",
                            Year = "1997"
                        },
                        new
                        {
                            Id = 27,
                            Copies = 3,
                            Genre = "crime, drama, fantasy",
                            Plot = "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
                            Title = "The Green Mile",
                            Year = "1999"
                        },
                        new
                        {
                            Id = 28,
                            Copies = 3,
                            Genre = "action, adventure, fantasy",
                            Plot = "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her 10-year old son John from an even more advanced and powerful cyborg.",
                            Title = "Star Wars",
                            Year = "1977"
                        },
                        new
                        {
                            Id = 29,
                            Copies = 3,
                            Genre = "action, sci-fi, thriller",
                            Plot = "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.",
                            Title = "Terminator 2: Judgment Day",
                            Year = "1991"
                        },
                        new
                        {
                            Id = 30,
                            Copies = 3,
                            Genre = "adventure, comedy, sci-fi",
                            Plot = "Farmers from a village exploited by bandits hire a veteran samurai for protection, who gathers six other samurai to join him.",
                            Title = "Back to the Future",
                            Year = "1985"
                        },
                        new
                        {
                            Id = 31,
                            Copies = 3,
                            Genre = "adventure, animation, family",
                            Plot = "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
                            Title = "Spirited Away",
                            Year = "2001"
                        },
                        new
                        {
                            Id = 32,
                            Copies = 3,
                            Genre = "biography, drama, war",
                            Plot = "When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.",
                            Title = "The Pianist",
                            Year = "2002"
                        },
                        new
                        {
                            Id = 33,
                            Copies = 3,
                            Genre = "horror, mystery, thriller",
                            Plot = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Title = "Psycho",
                            Year = "1960"
                        },
                        new
                        {
                            Id = 34,
                            Copies = 3,
                            Genre = "drama, thriller",
                            Plot = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Title = "Parasite",
                            Year = "2019"
                        },
                        new
                        {
                            Id = 35,
                            Copies = 3,
                            Genre = "crime, drama, thriller",
                            Plot = "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
                            Title = "Léon: The Professional",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 36,
                            Copies = 3,
                            Genre = "action, drama",
                            Plot = "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
                            Title = "Gladiator",
                            Year = "2000"
                        },
                        new
                        {
                            Id = 37,
                            Copies = 3,
                            Genre = "adventure, animation, drama",
                            Plot = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
                            Title = "The Lion King",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 38,
                            Copies = 3,
                            Genre = "crime, drama",
                            Plot = "12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.",
                            Title = "American History X",
                            Year = "1998"
                        },
                        new
                        {
                            Id = 39,
                            Copies = 3,
                            Genre = "crime, drama, thriller",
                            Plot = "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
                            Title = "The Departed",
                            Year = "2006"
                        },
                        new
                        {
                            Id = 40,
                            Copies = 3,
                            Genre = "drama, music",
                            Plot = "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
                            Title = "Whiplash",
                            Year = "2014"
                        },
                        new
                        {
                            Id = 41,
                            Copies = 3,
                            Genre = "drama, mystery, thriller",
                            Plot = "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
                            Title = "The Prestige",
                            Year = "2006"
                        },
                        new
                        {
                            Id = 42,
                            Copies = 3,
                            Genre = "crime, drama, thriller",
                            Plot = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            Title = "The Usual Suspects",
                            Year = "1995"
                        },
                        new
                        {
                            Id = 43,
                            Copies = 3,
                            Genre = "drama, romance, war",
                            Plot = "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a random police lineup.",
                            Title = "Casablanca",
                            Year = "1942"
                        },
                        new
                        {
                            Id = 44,
                            Copies = 3,
                            Genre = "animation, drama, war",
                            Plot = "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run and checks into a remote motel run by a young man under the domination of his mother.",
                            Title = "Hotaru no haka",
                            Year = "1988"
                        },
                        new
                        {
                            Id = 45,
                            Copies = 3,
                            Genre = "action, drama, history",
                            Plot = "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
                            Title = "Seppuku",
                            Year = "1962"
                        },
                        new
                        {
                            Id = 46,
                            Copies = 3,
                            Genre = "biography, comedy, drama",
                            Plot = "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
                            Title = "Intouchables",
                            Year = "2011"
                        },
                        new
                        {
                            Id = 47,
                            Copies = 3,
                            Genre = "comedy, drama",
                            Plot = "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.",
                            Title = "Modern Times",
                            Year = "1936"
                        },
                        new
                        {
                            Id = 48,
                            Copies = 3,
                            Genre = "western",
                            Plot = "A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.",
                            Title = "C'era una volta il West",
                            Year = "1968"
                        },
                        new
                        {
                            Id = 49,
                            Copies = 3,
                            Genre = "drama",
                            Plot = "A young boy and his little sister struggle to survive in Japan during World War II.",
                            Title = "Nuovo Cinema Paradiso",
                            Year = "1988"
                        },
                        new
                        {
                            Id = 50,
                            Copies = 3,
                            Genre = "mystery, thriller",
                            Plot = "A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema's projectionist.",
                            Title = "Rear Window",
                            Year = "1954"
                        });
                });

            modelBuilder.Entity("MovieRental.Model.RentedMovie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MovieId");

                    b.ToTable("RentedMovie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateIssued = new DateTime(2023, 5, 19, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1132),
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 4,
                            DateIssued = new DateTime(2023, 5, 19, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1176),
                            MovieId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 14,
                            DateIssued = new DateTime(2023, 5, 17, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1179),
                            MovieId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 1,
                            DateIssued = new DateTime(2023, 4, 21, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1181),
                            DateReturned = new DateTime(2023, 5, 19, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1183),
                            MovieId = 4
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 11,
                            DateIssued = new DateTime(2023, 5, 18, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1186),
                            MovieId = 5
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 7,
                            DateIssued = new DateTime(2023, 5, 18, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1188),
                            MovieId = 6
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 4,
                            DateIssued = new DateTime(2023, 5, 12, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1190),
                            DateReturned = new DateTime(2023, 5, 19, 15, 23, 11, 955, DateTimeKind.Local).AddTicks(1191),
                            MovieId = 7
                        });
                });

            modelBuilder.Entity("MovieRental.Model.RentedMovie", b =>
                {
                    b.HasOne("MovieRental.Model.Customer", "Customer")
                        .WithMany("RentedMovies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieRental.Model.Movie", "Movie")
                        .WithMany("RentedMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieRental.Model.Customer", b =>
                {
                    b.Navigation("RentedMovies");
                });

            modelBuilder.Entity("MovieRental.Model.Movie", b =>
                {
                    b.Navigation("RentedMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
